store/api/urls.py
from django.urls import path, include, re_path
from rest_framework.routers import DefaultRouter

from api.views import products, ProductDetailView, comments, APICategoryViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView, TokenVerifyView,
)
router = DefaultRouter()
router.register('categories', APICategoryViewSet)

urlpatterns = [
    path('products/<int:pk>/comments/', comments),
    path('products/<int:pk>', ProductDetailView.as_view()),
    path('products/', products),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),  # JWT authentication
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('drf-auth/', include('rest_framework.urls')),  # session based authentication
    re_path(r'^auth/', include('djoser.urls')),  # token based authentication
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('', include(router.urls)),
]

store/main/urls.py
from django.urls import path

from .views import index, other_page, detail, StoreLoginView, profile, StoreLogoutView, ChangeInfoUserFormView, \
    UserPasswordChangeView, RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_category, \
    profile_product_detail, profile_product_add, profile_product_change, profile_product_delete

app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/change/<int:pk>/', profile_product_change, name='profile_product_change'),
    path('accounts/profile/delete/<int:pk>/', profile_product_delete, name='profile_product_delete'),
    path('accounts/profile/add/', profile_product_add, name='profile_product_add'),
    path('accounts/profile/<int:pk>/', profile_product_detail, name='profile_product_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/delete', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeInfoUserFormView.as_view(), name='profile_change'),
    path('accounts/login/', StoreLoginView.as_view(), name='login'),
    path('accounts/logout/', StoreLogoutView.as_view(), name='logout'),
    path('accounts/password/change', UserPasswordChangeView.as_view(), name='password_change'),
    path('<int:category_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_category, name='by_category'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

store/store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/main/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from .apps import user_registered
from .models import AdvUser, SuperCategory, SubCategory, Product, AdditionalImage, Comment


class ChangeInfoUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(
        label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        label='Пароль(повторно)', widget=forms.PasswordInput, help_text='Пожалуйста, введите пароль еще раз'
    )

    def clean_password(self):
        """Проверка правильности ввода первого пароля"""
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        """Проверка совпадения двух паролей"""
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        """Сохранение нового пользователя"""
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')


class SubCategoryForm(forms.ModelForm):
    super_category = forms.ModelChoiceField(
        queryset=SuperCategory.objects.all(), empty_label=None, label='Надкатегория', required=True
    )

    class Meta:
        model = SubCategory
        fields = '__all__'


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {'seller': forms.HiddenInput}


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = {'is_active',}
        widgets = {'product': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с изображения', error_messages={'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = {'is_active',}
        widgets = {'product': forms.HiddenInput}


AIFormSet = inlineformset_factory(Product, AdditionalImage, fields='__all__')

store/main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.core.signing import BadSignature
from django.db.models import Q
from django.db.models.signals import post_save
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView

from .forms import ChangeInfoUserForm, RegisterUserForm, SearchForm, ProductForm, AIFormSet, UserCommentForm, \
    GuestCommentForm
from .models import AdvUser, SubCategory, Product, Comment
from .utilites import signer, send_new_comment_notification


def index(request):
    products = Product.objects.filter(is_active=True)[:20]
    context = {
        'products': products,
    }
    return render(request, 'main/index.html', context)


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


@login_required
def profile(request):
    products = Product.objects.filter(seller=request.user.pk)
    context = {
        'products': products
    }
    return render(request, 'main/profile.html', context)


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class StoreLoginView(LoginView):
    template_name = 'main/login.html'


class StoreLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeInfoUserFormView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeInfoUserForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя успешно изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class UserPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Ваш пароль изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def by_category(request, pk):
    category = get_object_or_404(SubCategory, pk=pk)
    products = Product.objects.filter(is_active=True, category=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        products = products.filter(q)
    else:
        keyword = ''
        form = SearchForm(initial={'keyword': keyword})
        paginator = Paginator(products, 2)
        if 'page' in request.GET:
            page_num = request.GET['page']
        else:
            page_num = 1
        page = paginator.get_page(page_num)
        context = {
            'category': category,
            'page': page,
            'products': page.object_list,
            'form': form
        }
        return render(request, 'main/by_category.html', context)


def detail(request, category_pk, pk):
    product = get_object_or_404(Product, pk=pk)
    ais = product.additionalimage_set.all()
    comments = Comment.objects.filter(product=pk, is_active=True)
    initial = {'product': product.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
    context = {
        'product': product,
        'ais': ais,
        'comments': comments,
        'form': form
    }
    return render(request, 'main/detail.html', context)


@login_required
def profile_product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    ais = product.additionalimage_set.all()
    context = {
        'product': product,
        'ais': ais,
    }
    return render(request, 'main/profile_product_detail.html', context)


@login_required
def profile_product_add(request):
    """Контроллер для добавления товара"""
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Товар добавлен')
                return redirect('main:profile')
    else:
        form = ProductForm(initial={'seller': request.user.pk})
        formset = AIFormSet()
    context = {
        'form': form,
        'formset': formset
    }
    return render(request, 'main/profile_product_add.html', context)


@login_required
def profile_product_change(request, pk):
    """Контроллер для изменения товара"""
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Информация о товаре изменена')
                return redirect('main:profile')
    else:
        form = ProductForm(instance=product)
        formset = AIFormSet(instance=product)
    context = {
        'form': form,
        'formset': formset
    }
    return render(request, 'main/profile_product_change.html', context)


@login_required
def profile_product_delete(request, pk):
    """Контроллер для удаления товара"""
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        messages.add_message(request, messages.SUCCESS, 'Информация о товаре удалена')
        return redirect('main:profile')
    else:
        context = {
            'product': product
        }
        return render(request, 'main/profile_product_delete.html', context)


def post_save_dispatcher(sender, **kwargs):
    author = kwargs['instance'].product.seller
    if kwargs['created'] and author.send_messages:
        send_new_comment_notification(kwargs['instance'])


post_save.connect(post_save_dispatcher, sender=Comment)

store/main/templates/main/about.html
{% extends 'layout/basic.html' %}

{% block title%} О сайте {% endblock %}

{% block content %}
<h2>Магазин</h2>
{% endblock %}

store/main/templates/main/activation_done.html
{% extends 'layout/basic.html' %}

{% block title%}Активация выполнена{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя завершена</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

store/main/templates/main/bad_signature.html
{% extends 'layout/basic.html' %}

{% block title%}Ошибка при активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>При активации пользователя произошла ошибка</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться на сайте</a></p>
{% endblock %}

store/main/templates/main/by_category.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title%} {{ category }} {% endblock %}

{% block content %}
<h2 class="mb-2">{{ category }}</h2>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
</div>
{% if products %}
<ul class="list-unstyled">
    {% for product in products %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' category_pk=category.pk pk=product.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if product.image %}
            <img class="mr-3" src="{% thumbnail product.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.jpg' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">{{ product.title }}</a></h3>
            <div>{{ product.content }}</div>
            <p class="text-right font-weight-bold"> Цена: {{ product.price }} руб.</p>
            <p class="text-right font-italic">Добавлено: {{ product.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

store/main/templates/main/change_user_info.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title%}Правка данных пользователя{% endblock %}

{% block content %}
<h3>Здесь Вы можете изменить свои данные</h3>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %} {% endbuttons %}
</form>
{% endblock %}

store/main/templates/main/detail.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}
{% block title%} {{ product.title }} - {{ product.category.name }} {% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if product.image %}
        <div class="col-md-auto"><img src="{{ product.image.url }}" class="main-image"> </div>
        {% endif %}
        <div class="col">
            <h2>{{ product.title }}</h2>
            <p>Описание: {{ product.content }}</p>
            <p class="font-weight-bold"> Цена: {{ product.price }} руб.</p>
            <p>Производитель: {{ product.manufacturer }}</p>
            <p class="text-right font-italic"> Добавлено {{ product.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:by_category' pk=product.pk %}{{ all }}">Назад</a> </p>
<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %} {% endbuttons %}
</form>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

store/main/templates/main/login.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title%} Вход {% endblock %}

{% block content %}
{% if user.is_authenticated %}
<p>Вы уже выполнили вход</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
<h2>Вход</h2>
{% endblock %}

store/main/templates/main/logout.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title%} Выход {% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно покинули сайт</p>
{% endblock %}

store/main/templates/main/profile.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title%} Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p>
{% elif  user.first_name %}
<p>Здравствуйте, {{ user.first_name }}</p>
{% else %}
<p>Здравствуйте</p>
{% endif %}
<h3>Ваши товары:</h3>
{% if products %}
<ul class="list-unstyled">
    {% for product in products %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_product_detail' pk=product.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if product.image %}
            <img class="mr-3" src="{% thumbnail product.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.jpg' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <p> Категория {{ product.category}}</p>
            <h3><a href="{{ url }}{{ all }}">{{ product.title }}</a></h3>
            <div>{{ product.content }}</div>
            <p class="text-right font-weight-bold">{{ product.price }} руб.</p>
            <p class="text-right font-italic">{{ product.created_at }}</p>
            <p class="text-right mt-2">
                <a href="{% url 'main:profile_product_change' pk=product.pk%}">Изменить</a>
                <a href="{% url 'main:profile_product_delete' pk=product.pk%}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
<p><a href="{% url 'main:profile_product_add' %}">'Добавить товар'</a> </p>
{% endblock %}

store/main/templates/main/profile_product_add.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title%} Добавление товара {% endblock %}

{% block content %}
<h2>Заполните форму для добавления товара</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% buttons submit='Добавить' %} {% endbuttons %}
</form>
{% endblock %}

store/main/templates/main/profile_product_change.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title%}Правка данных о товаре{% endblock %}

{% block content %}
<h3>Здесь Вы можете изменить информацию о товаре</h3>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %} {% endbuttons %}
</form>
{% endblock %}

store/main/templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% block title%}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
<p>На ваш адрес электронной почты выслано письмо для активации.</p>
{% endblock %}

store/main/templates/main/register_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title%}Регистрация{% endblock %}

{% block content %}
<h3>Регистрация нового пользователя</h3>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>
{% endblock %}

store/main/templates/main/user_is_activated.html
{% extends 'layout/basic.html' %}

{% block title%}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Вы уже активировались на сайте</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}